# Generated by Django 5.0.3 on 2024-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_store_name_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
        migrations.AddField(
            model_name='product',
            name='available_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_units',
            field=models.IntegerField(default=0),
        ),
    ]
